version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: book_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_manager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: book_backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: book_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  db_data: 